bucket               = "devops-demo.tfstate"
key                  = "argocdinfra.json"
region               = "eu-west-1"
workspace_key_prefix = "environment"
dynamodb_table       = "devops-demo.tfstate.lock"
