# bucket               = "devops-demo.tfstate"
# key                  = "argocd.json"
# region               = "us-east-1"
# workspace_key_prefix = "environment"
# dynamodb_table       = "devops-demo.tfstate.lock"
